# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.IntegerField(default=2),
        ),
    ]
